// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbBd-MuyXEfrA8IcyyjUYTRUMwXzLbYg',
    appId: '1:1005384776512:web:09cc91ba4efe23fa0e58a5',
    messagingSenderId: '1005384776512',
    projectId: 'smartpal-79c28',
    authDomain: 'smartpal-79c28.firebaseapp.com',
    storageBucket: 'smartpal-79c28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pbVhJ5xLhFbh9qOHcOGcAonprwtUlP0',
    appId: '1:1005384776512:android:41a7f5e7978adb4d0e58a5',
    messagingSenderId: '1005384776512',
    projectId: 'smartpal-79c28',
    storageBucket: 'smartpal-79c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2x5viXUwYn9zmJg0Ge-yO4VhjlO-lgQQ',
    appId: '1:1005384776512:ios:82d9cc3d2dcdaa830e58a5',
    messagingSenderId: '1005384776512',
    projectId: 'smartpal-79c28',
    storageBucket: 'smartpal-79c28.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );
}
